# To use:
#
#   $ conda env create -f environment.yml  # can use `mamba` too
#   $ conda activate kde-ext
#
name: kde-ext
channels:
  - conda-forge
  - intel
dependencies:
  - python
  - cython
  - numpy
  - scikit-build-core
  - scikit-build
  - cmake>=3.27
  - ninja>=1.11.1
  - pybind11
