# To use:
#
#   $ conda env create -f environment.yml  # can use `mamba` too
#   $ conda activate kde-ext
#
name: kde-ext
channels:
  - conda-forge
  - intel
dependencies:
  - python
  - dpctl
  - numpy
  - pybind11
